/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.87
 * Generated at: 2024-04-12 02:03:33 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.dudu;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1710806271348L));
    _jspx_dependants.put("jar:file:/C:/Users/sec7/Desktop/eGovFrameDev-3.10.0-64bit/workspace5/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/duduCalendar/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\r\n");
      out.write("<link href=\"https://webfontworld.github.io/TheJamsil/TheJamsil.css\" rel=\"stylesheet\">\r\n");
      out.write("<title>비밀번호 초기화</title>\r\n");
      out.write("</head>\r\n");
      out.write("<style>\r\n");
      out.write("	body{\r\n");
      out.write("		background: #f6f5f7;\r\n");
      out.write("		font-family: 'TheJamsil';\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	form{\r\n");
      out.write("		background-color: #FFFFFF;\r\n");
      out.write("		display: flex;\r\n");
      out.write("		align-items: center;\r\n");
      out.write("		justify-content: center;\r\n");
      out.write("		flex-direction: column;\r\n");
      out.write("		width: 400px;\r\n");
      out.write("		text-align: center;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	input{\r\n");
      out.write("		width:70%;\r\n");
      out.write("		padding: 12px 15px;\r\n");
      out.write("		border: none;\r\n");
      out.write("		margin: 8px 0;\r\n");
      out.write("		background-color: #eee;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	button{\r\n");
      out.write("		border-radius: 4px;\r\n");
      out.write("		border: 1px solid #CEE3F6;\r\n");
      out.write("		background-color: #CEE3F6;\r\n");
      out.write("		color: #190707;\r\n");
      out.write("		font-size: 12px;\r\n");
      out.write("		font-weight: bold;\r\n");
      out.write("		padding: 12px 45px;\r\n");
      out.write("		letter-spacing: 1px;\r\n");
      out.write("		transition: transform 80ms ease-in;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	button.active{\r\n");
      out.write("		transform: scale(0.95);\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	button.focus{\r\n");
      out.write("		outline: none;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	button.ghost{\r\n");
      out.write("		background-color: transparent;\r\n");
      out.write("		border-color: #FFFFFF;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	img{\r\n");
      out.write("		width: 300px;\r\n");
      out.write("		height:150px;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.modal{\r\n");
      out.write("		position: absolute;\r\n");
      out.write("		display: none;\r\n");
      out.write("		justify-content: center;\r\n");
      out.write("		top:0;\r\n");
      out.write("		left:0;\r\n");
      out.write("		width: 100%;\r\n");
      out.write("		height: 100%;\r\n");
      out.write("		background-color: rgba(0,0,0,0.4);\r\n");
      out.write("	}\r\n");
      out.write("	.modal2{\r\n");
      out.write("		position: absolute;\r\n");
      out.write("		display: none;\r\n");
      out.write("		justify-content: center;\r\n");
      out.write("		top:0;\r\n");
      out.write("		left:0;\r\n");
      out.write("		width: 100%;\r\n");
      out.write("		height: 100%;\r\n");
      out.write("		background-color: rgba(0,0,0,0.4);\r\n");
      out.write("	}\r\n");
      out.write("	.modal_body{\r\n");
      out.write("		position: absolute;\r\n");
      out.write("		top:50%;\r\n");
      out.write("		width: 400px;\r\n");
      out.write("		padding: 40px;\r\n");
      out.write("		text-align: center;\r\n");
      out.write("		background-color: rgb(255,255,255);\r\n");
      out.write("		border-radius: 10px;\r\n");
      out.write("		box-shadow: 0 2px 3px 0 rgba(34,36,38,0.15);\r\n");
      out.write("		transform: translateY(-50%);\r\n");
      out.write("	}\r\n");
      out.write("	.send{\r\n");
      out.write("		width:500px;\r\n");
      out.write("		height: 550px;\r\n");
      out.write("		border-radius: 5px;\r\n");
      out.write("		box-shadow: 0px 2px 10px 2px rgba(0,0,0,0.3);\r\n");
      out.write("		display: flex;\r\n");
      out.write("		justify-content:center;\r\n");
      out.write("		margin:150px auto 0px;	\r\n");
      out.write("		background-color: white;\r\n");
      out.write("	}\r\n");
      out.write("</style>\r\n");
      out.write("<body>	\r\n");
      out.write("<div class=\"send\">\r\n");
      out.write("	<form action=\"send.do\" name=\"sub1\" method=\"POST\">\r\n");
      out.write("		<img src=\"");
      if (_jspx_meth_c_005furl_005f0(_jspx_page_context))
        return;
      out.write("\">\r\n");
      out.write("		<input type=\"text\" id=\"username\" name=\"username\" placeholder=\"name\"/>\r\n");
      out.write("		<input type=\"email\" id=\"useremail\" name=\"useremail\" placeholder=\"email\"/>\r\n");
      out.write("		<button id=\"open\">비밀번호 발급</button>\r\n");
      out.write("\r\n");
      out.write("	</form>\r\n");
      out.write("	</div>\r\n");
      out.write("	<div class=\"modal\">\r\n");
      out.write("		<div class=\"modal_body\">\r\n");
      out.write("			<h2>인증번호 확인</h2>\r\n");
      out.write("			<input type=\"text\" id=\"no\" placeholder=\"number\">\r\n");
      out.write("			<button id=\"chk\">인증번호 확인</button>\r\n");
      out.write("			<button id=\"x\">취소</button>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("	<div class=\"modal2\">\r\n");
      out.write("		<div class=\"modal_body\">\r\n");
      out.write("		<form action=\"updatepwd.do\" name=\"sub2\">\r\n");
      out.write("			<h2>비밀번호 변경</h2>\r\n");
      out.write("			<input type=\"password\" name=\"entrprsMberPassword\" id=\"entrprsMberPassword\" placeholder=\"변경할 비밀번호\">\r\n");
      out.write("			<input type=\"password\" id=\"pwchk\" placeholder=\"변경할 비밀번호 확인\">\r\n");
      out.write("			<div>\r\n");
      out.write("			<input type=\"button\" id=\"pwd\">확인</button>\r\n");
      out.write("			<input type=\"button\" id=\"x1\">취소</button>\r\n");
      out.write("			</div>\r\n");
      out.write("			<input type=\"hidden\" name=\"applcntEmailAdres\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.useremail}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("			</form>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("	const open = document.getElementById(\"open\");\r\n");
      out.write("	const chk = document.getElementById(\"chk\");\r\n");
      out.write("	const modal = document.querySelector('.modal');\r\n");
      out.write("	const x = document.getElementById('x');\r\n");
      out.write("	const x1 = document.getElementById('x1');\r\n");
      out.write("	const modal2 = document.querySelector('.modal2');\r\n");
      out.write("	const pwd = document.getElementById(\"pwd\");\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	pwd.onclick = function(){\r\n");
      out.write("		var pwInput = $('#entrprsMberPassword').val();	\r\n");
      out.write("		var pwRegex = /^(?=.*[a-zA-Z])(?=.*\\d)(?=.*[!@#$%^&*()_+])[A-Za-z\\d!@#$%^&*()_+]{6,20}$/;\r\n");
      out.write("		\r\n");
      out.write("		if (!pwRegex.test(pwInput)) {\r\n");
      out.write("            alert(\"비밀번호는 영문, 숫자, 특수문자를 각각 1개 이상 포함하여 6~20 글자로 사용해야 합니다.\");\r\n");
      out.write("            return false;\r\n");
      out.write("		}\r\n");
      out.write("		if($('#entrprsMberPassword').val() != $('#pwchk').val()){\r\n");
      out.write("  			alert(\"비밀번호가 다릅니다.\");\r\n");
      out.write("            return false;\r\n");
      out.write("		}else{\r\n");
      out.write("			document.sub2.submit();\r\n");
      out.write("		}\r\n");
      out.write("			\r\n");
      out.write("	}\r\n");
      out.write("	");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	open.onclick = function(){\r\n");
      out.write("		var count = 0;\r\n");
      out.write("		var count2 = 0;\r\n");
      out.write("		");
      if (_jspx_meth_c_005fforEach_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		if(count == 1 && count2 == 1){\r\n");
      out.write("			document.sub1.submit();\r\n");
      out.write("		}\r\n");
      out.write("		else if(count == 0){\r\n");
      out.write("			alert(\"가입된 이메일이 없습니다.\");\r\n");
      out.write("			return false;\r\n");
      out.write("		}\r\n");
      out.write("		else if(count2 == 0){\r\n");
      out.write("			alert(\"이름과 이메일이 일치하지 않습니다.\")\r\n");
      out.write("			return false;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		if($('#username').val() == \"\"){\r\n");
      out.write("			alert(\"이름을 입력해주세요\");\r\n");
      out.write("			return false;\r\n");
      out.write("		}\r\n");
      out.write("		else if($('#usereamil').val()==\"\"){\r\n");
      out.write("			alert(\"이메일을 입력해주세요\");\r\n");
      out.write("			return false;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	window.onload=function(){\r\n");
      out.write("		if(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.useremail}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"){\r\n");
      out.write("			modal.style.display=\"flex\";\r\n");
      out.write("		}\r\n");
      out.write("		else{\r\n");
      out.write("			modal.style.display=\"none\";\r\n");
      out.write("		}\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	chk.onclick = function (){\r\n");
      out.write("		const chk = document.getElementById(\"no\").value;\r\n");
      out.write("		const pw = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.message}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"\r\n");
      out.write("		console.log(chk);\r\n");
      out.write("		console.log(pw);\r\n");
      out.write("		if(chk==\"\"){\r\n");
      out.write("			alert(\"인증번호를 입력해주세요\");\r\n");
      out.write("			return false;\r\n");
      out.write("			\r\n");
      out.write("		}\r\n");
      out.write("		else if(chk==pw){\r\n");
      out.write("			alert(\"확인 완료\");\r\n");
      out.write("			modal.style.display=\"none\";\r\n");
      out.write("			modal2.style.display=\"flex\";\r\n");
      out.write("		}\r\n");
      out.write("		else{\r\n");
      out.write("			alert(\"인증번호가 정확하지 않습니다.\");\r\n");
      out.write("			return false;\r\n");
      out.write("		}\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	x.onclick = function(){\r\n");
      out.write("		modal.style.display=\"none\";\r\n");
      out.write("		\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	x1.onclick = function(){\r\n");
      out.write("		modal2.style.display=\"none\";\r\n");
      out.write("		\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f0_reused = false;
    try {
      _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f0.setParent(null);
      // /WEB-INF/jsp/dudu/main.jsp(111,12) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f0.setValue("/images/dudu/blue_duduCalendar_logo.svg");
      int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
      if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
      _jspx_th_c_005furl_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f0, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/jsp/dudu/main.jsp(173,1) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/jsp/dudu/main.jsp(173,1) '${userlist}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${userlist}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /WEB-INF/jsp/dudu/main.jsp(173,1) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("userlist");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("	console.log(\"userlist = ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userlist.useremail}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\");\r\n");
            out.write("	");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f1_reused = false;
    try {
      _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f1.setParent(null);
      // /WEB-INF/jsp/dudu/main.jsp(180,2) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/jsp/dudu/main.jsp(180,2) '${userlist}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${userlist}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /WEB-INF/jsp/dudu/main.jsp(180,2) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setVar("userlist");
      int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
        if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("		console.log(\"userlist = ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userlist.useremail}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\");\r\n");
            out.write("		if($('#useremail').val() == \"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userlist.useremail}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\"){\r\n");
            out.write("			count = 1;\r\n");
            out.write("		}\r\n");
            out.write("		if($('#username').val()==\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userlist.username}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\"){\r\n");
            out.write("			count2 = 1;\r\n");
            out.write("		}\r\n");
            out.write("		");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f1);
      _jspx_th_c_005fforEach_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f1_reused);
    }
    return false;
  }
}
